Numpy
==

* Numpy (Numerical Python) : 배열(행렬) 기반 계산 위해 C언어로 구현된 파이썬 라이브러리

>  - N 차원 배열 객체 (동일 자료형 데이터 저장)

>  - 고속 in-memory 계산 (단일 연속 메모리 블록 사용)

>  - 정교한 브로드캐스팅 기능
>>  - 브로드캐스팅? 송신 호스트가 전송한 데이터가 네트워크에 연결된 모든 호스트에 전송

>  - C/C++ 및 Fortran 코드 통합 도구

>  - 선형 대수학, 푸리에 변환 및 난수 기능

>  - 범용 데이터 처리에 사용 가능한 다차원 컨테이너

* Numpy 배열 특징
>  - Python 기본 자료형 'List'
>>  - list 객체 인스턴스는 다양한 타입의 객체 보관 가능

In [1278]:
L1 = list(range(10))
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1279]:
L2 = [True, "2", 3.0, 4]
print(type(L2))

<class 'list'>


In [1280]:
[type(item) for item in L2]

[bool, str, float, int]

In [1281]:
[id(item) for item in L2]

[7634048, 140160301790640, 140156918934320, 140160323926416]

* Python의 Array 모듈
>  - array.array 객체 인스턴스는 고정 타입의 객체 보관

In [1282]:
import array

L = list(range(10))
A = array.array('i', L)

In [1283]:
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [1284]:
type(A)

array.array

* 궁금한 점
>  - typecode 의미와 그 쓰임새
>  - tolist( )와 다른 점?
>  - 왜 typecode는 buffer에 없는 걸까?

In [ ]:
'''

class array():
   def __init__(self, ...,):
      self.typecode = i

   def tolist(self, ...,):
      ...
      array 내용을 하나하나 다루는 코드
      ...
      return [array 내용]

'''

In [1286]:
print(A.typecode)

i


In [1287]:
print(A.tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1288]:
print(A.buffer_info())

# 배열의 내용을 담는 데, 사용된 버퍼( 임시 저장 공간 - 메모리와 화면 사이에 존재하는 저장공간 )의 현재 메모리 주소(id)와 요소의 수

(140156918384368, 10)


* Python Numpy Array
>  - Numpy array 객체 인스턴스는 형 정보 보관

In [1289]:
import numpy as np

nda1 = np.array([1, 4, 2, 5, 3])

In [1290]:
print(nda1.shape)

# 배열 형태(shape)

(5,)


In [1291]:
print(nda1.dtype)

# 배열 자료형

int64


In [1292]:
print(nda1.ndim)

# 배열 차원

1


In [1293]:
print(nda1.strides)

# 각 요소의 크기

(8,)


In [1294]:
print(nda1.data.tolist())

[1, 4, 2, 5, 3]


In [1295]:
nda2 = np.array([3.14, 4, 2, 3])
nda2

# 서로 다른 형의 값을 입력하면, 정보가 저장가능한 타입으로 변환됨

array([3.14, 4.  , 2.  , 3.  ])

In [1296]:
print(nda2.dtype)

float64


In [1297]:
nda3 = np.array([1, 2, 3, 4], dtype='float32') # 자료형 지정
nda3

array([1., 2., 3., 4.], dtype=float32)

* Numpy 데이터 생성

>  - Numpy 자료형
>>  - int8, int16, int32, int64 ( 음수와 양수를 다 아우르는 정수형 자료형 )
>>  - unit8, unit16, uint32, uint64 ( 0 포함한 양수 or 부호없는 정수를 제공하는 자료형 )
>>  - float16, float32, float64
>>  - complex64, complex128 ( 복소수형 자료형 )


>  - 스칼라( scalar ) 데이터

In [1298]:
import numpy as np

x = np.float32(1.0)
x

1.0

>  - 배열 데이터

In [1299]:
np.array([1, 2, 3]) 

# 1차원 배열

array([1, 2, 3])

In [1300]:
y = np.array([[1,2], [3,4]])
y

# 2차원 배열

array([[1, 2],
       [3, 4]])

In [1301]:
y.shape

(2, 2)

In [1302]:
z = np.array([1, 2, 3], ndmin=2)
z

# 최소 차원 지정
# ndim : 최소 차원수

array([[1, 2, 3]])

In [1303]:
z.shape

(1, 3)

In [1304]:
z.ndim

2

In [1305]:
np.array([1, 2, 3], dtype=complex)

# 자료형 지정

array([1.+0.j, 2.+0.j, 3.+0.j])

>  - 특별한 값의 배열 생성 ( 초기화 )

In [1306]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [1307]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [1308]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [1309]:
np.arange(3, 10, 2)

# (시작값, 종료값, 간격)

array([3, 5, 7, 9])

In [1310]:
np.arange(3, 10, 2, dtype=float)

# 자료형 지정

array([3., 5., 7., 9.])

In [1311]:
np.zeros(5)

# 자료(배열) 형 형태, 기본 자료형: float64

array([0., 0., 0., 0., 0.])

In [1312]:
a = np.zeros((2,3), dtype=int)
a

# 자료형 지정

array([[0, 0, 0],
       [0, 0, 0]])

In [1313]:
b = np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [1314]:
c = np.ones((3,2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [1315]:
d = np.ones_like(c, dtype=int)
d

# 형 지정

array([[1, 1],
       [1, 1],
       [1, 1]])

In [1316]:
e = np.ones_like(c)
e

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [1317]:
np.full((2,3), 7)

# 지정 shape의 배열 생성 후, 모든 요소 지정 값으로 초기화

array([[7, 7, 7],
       [7, 7, 7]])

In [1318]:
np.eye(4)

# (N, N) shape의 단위 행렬( Unit Matrix ) 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1319]:
a = np.empty((4,2))
print(a)

# 지정된 shape의 배열을 생성. 요소의 초기화 과정 없이, 기존 메모리 값을 그대로 사용
# 배열 생성비용이 가장 저렴하고 빠름. 하지만 사용 시 값 부여 필수

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]


In [1320]:
np.linspace(1., 4., 6)

# 일정한 간격으로 지정된 갯수만큼 배열의 원소 생성
# (처음 값, 마지막 값, 원소 수)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [1321]:
np.linspace(1., 4., 6, endpoint=False)

# 마지막 값은 포함하지 않음

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [1322]:
np.random.randn(2,3)

# 정규 분포 난수

array([[-0.35725084,  1.39349626,  1.95296916],
       [ 0.51023335,  0.74215852, -1.41868353]])

In [1323]:
np.random.randint(5, 10, size=(2,4))

# (시작값, 종료값, shape)

array([[9, 6, 5, 8],
       [9, 9, 6, 8]])

>  - Numpy 배열 기본 연산
>>  - 배열 정보 확인

In [1324]:
na = np.random.randn(2,3)
print(na.shape)

# 배열 형태

(2, 3)


In [1325]:
na

array([[ 0.06922241,  0.07588595, -1.0164788 ],
       [-0.65224787,  1.33098886, -1.34957017]])

In [1326]:
print(na.dtype)

# 배열 자료형

float64


In [1327]:
print(na.ndim)

# 배열 차원

2


* 궁금한 점
>  - 차원 별 요소 크기란?
>>  - 2차원 배열에서 첫번 째 차원 의 요소는 각 list 
>>  - 2차원에서 두번째 차원의 요소는 list안의 각 숫자
>>  - 데이터 형식 별 크기가 다른데, 숫자의 크기는 8
>>  - 크기가 8인 각 숫자가 하나의 list를 이루고 있으면, 8*3 = 24

In [1328]:
print(na.strides)

# 차원 별 요소 크기

(24, 8)


In [1329]:
print(na.size)

# 배열 전체 요소수

6


In [1330]:
nb = np.arange(10)
print(nb.shape)

# 1차원 배열의 shape

(10,)


In [1331]:
np.zeros(2)

array([0., 0.])

In [1332]:
np.zeros((2,1))

# 2행 1열. 2차원 배열

array([[0.],
       [0.]])

>  - 배열 변환

In [1333]:
print(na)
nb = na.astype(int)

# 지정된 형으로 배열 요소 형 변환

[[ 0.06922241  0.07588595 -1.0164788 ]
 [-0.65224787  1.33098886 -1.34957017]]


In [1334]:
print(nb)

[[ 0  0 -1]
 [ 0  1 -1]]


In [1335]:
a = np.arange(1, 9)
print(a)

[1 2 3 4 5 6 7 8]


In [1336]:
# 배열 shape 변환

b = a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1337]:
# transpose (전치행렬)

c = b.T
print(c)

[[1 3 5 7]
 [2 4 6 8]]


In [1338]:
print(c.shape)

(2, 4)


In [1339]:
np.info(np.ndarray.astype)

# 도움말

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

>  - Indexing

In [1340]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1341]:
print(x[0])

# 첫 요소

0


In [1342]:
print(x[2])

2


In [1343]:
print(x[8])

8


In [1344]:
print(x[-2])

# 끝에서 두 번째 요소

8


In [1345]:
x.shape = (2,5)
print(x)

# shape를 변환하는 또 다른 방법

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [1346]:
print(x[1,3])

8


In [1347]:
print(x[0,-1])

4


>  - Boolean indexing
>>  - 배열 각 요소의 선택 여부를 True, False 지정
>>  - 해당 인덱스의 True만 조회

In [1348]:
a1 = np.arange(1, 25).reshape((4, 6)) # 2차원 배열 4행 6열
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [1349]:
even_arr = (a1%2==0)
print(even_arr)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [1350]:
print(a1[even_arr])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [1351]:
print(a1[a1%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


>  - Fancy Indexing
>>  - 배열에 인덱스 배열을 전달해, 요소 참조

In [1352]:
arr = np.arange(1, 25).reshape((4, 6))
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [1353]:
[arr[0,0], arr[1,1], arr[2,2], arr[3,3]]

[1, 8, 15, 22]

In [1354]:
arr[[0, 1, 2, 3], [0, 1, 2, 3]]

# 두 배열을 전달 -> (0,0), (1,1), (2,2), (3,3)

array([ 1,  8, 15, 22])

*  복사와 Broadcasting
>  - 배열 간 연산

In [1355]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1356]:
b = np.arange(9, 0, -1).reshape(3, 3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [1357]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [1358]:
np.subtract(a, b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [1359]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [1360]:
np.add(a, b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [1361]:
a / b

# == np.divide(a,b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [1362]:
a * b

# == np.multiply(a,b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [1363]:
np.dot(a, b)

# 내적 (dot product)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [1364]:
a @ b

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [1365]:
a == b

# 배열 요소 별 비교

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [1366]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [1367]:
np.array_equal(a, b)

# 전체 배열 비교

False

* Broadcasting
>  - 두 배열 간의 Shape가 다를 경우, 두 배열 간 형상을 맞춰 계산

In [1368]:
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [1369]:
print(a+100)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [1370]:
a = np.arange(5).reshape((1, 5))
print(a)

[[0 1 2 3 4]]


In [1371]:
b = np.arange(5).reshape((5, 1))
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [1372]:
# 배열과 배열 연산

print(a+b)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


>  - 배열 복사

In [1373]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [1374]:
new = arr
print(new)

[1 2 3]


In [1375]:
new[0] = 3
print(new)

[3 2 3]


In [1376]:
print(arr)

[3 2 3]


In [1377]:
a = np.random.randint(0, 9, (3, 3))
a

array([[3, 8, 0],
       [1, 3, 7],
       [0, 0, 1]])

In [1378]:
b = np.copy(a)
b

array([[3, 8, 0],
       [1, 3, 7],
       [0, 0, 1]])

In [1379]:
a[0,0] = 0
a

array([[0, 8, 0],
       [1, 3, 7],
       [0, 0, 1]])

In [1380]:
b

array([[3, 8, 0],
       [1, 3, 7],
       [0, 0, 1]])

In [1381]:
arr = np.array([1,2,3])
new = arr.view()
new[0] = 3
print(arr)

# view : 동일 데이터 공간을 새롭게 보기

[3 2 3]


In [1382]:
print(new)

[3 2 3]


In [1383]:
arr = np.array([1,2,3,4], dtype='int16')
new = arr.view('int32')
print(arr)

# int16 => 2^16개 정수표현 가능
# int32 => 2^32개 정수표현 가능

[1 2 3 4]


In [1384]:
print(arr.shape)

(4,)


In [1385]:
print(new)

[131073 262147]


In [1386]:
print(new.shape)

(2,)


* 집계 (Aggrefate) 함수
>  - NumPy의 모든 집계 함수는 axis 기준으로 계산
>  - 집계함수에 axis 미지정 시 axis = None

>  - 전체 행렬을 하나의 배열로 간주, 집계 함수의 범위를 전체 행렬로 정의
>  - 전체 행과 열이 사라져서 집계

In [1387]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 9).reshape(4, 2)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1388]:
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1389]:
np.sum(a)

45

In [1390]:
a.sum()

45

In [1391]:
np.sum(a, axis=None)

45

In [1392]:
np.sum(b, axis=None)

36

In [1393]:
b.sum()

36

* axis = 0
>  - 행
>  - 행을 기준으로 각 행의 동일 인덱스의 요소를 그룹으로 함. 각 그룹을 집계 함수의 범위로 정의
>  - 0번째 차원(행)이 압축

In [1394]:
a = np.arange(1, 10).reshape(3, 3)

In [1395]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1396]:
np.sum(a, axis=0)

array([12, 15, 18])

In [1397]:
b = np.arange(1, 9).reshape(4, 2)

In [1398]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [1399]:
np.sum(b, axis=0)

array([16, 20])

* axis = 1
>  - 열
>  - 열을 기준으로 각 열의 요소를 그룹으로 함. 각 그룹을 집계 함수의 범위로 정의
>  - 1번째 차원(열)이 압축

In [1400]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1401]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [1402]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [1403]:
np.sum(b, axis=1)

array([ 3,  7, 11, 15])

In [1404]:
np.min(a, axis=1)

# == a.min(axis=0)

array([1, 4, 7])

In [1405]:
np.max(a, axis=0)

# == a.max(axis=1)

array([7, 8, 9])

In [1406]:
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1407]:
np.argmin(b, axis=1)

# 최소인덱스

array([0, 0, 0, 0])

In [1408]:
np.argmax(b, axis=0)

# 최대인덱스

array([3, 3])

In [1409]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1410]:
np.mean(a, axis=0)

# == a.mean(axis=0)

# 평균

array([4., 5., 6.])

In [1411]:
np.mean(a, axis=1)

# == a.mean(axis=1)

array([2., 5., 8.])

In [1412]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1413]:
print(np.median(a, axis=0))

# 중앙값

[4. 5. 6.]


In [1414]:
print(np.median(a, axis=1))

# 중앙값

[2. 5. 8.]


In [1415]:
print(np.std(a, axis=0))

# 표준편차

[2.44948974 2.44948974 2.44948974]


In [1416]:
print(np.std(a, axis=1))

# 표준편차

[0.81649658 0.81649658 0.81649658]


* 정렬

In [1417]:
unsorted_arr = np.random.rand(3, 3)
print(unsorted_arr)

[[0.11557521 0.0845008  0.15335899]
 [0.04175934 0.35801565 0.06661383]
 [0.59773814 0.45941345 0.23126106]]


In [1418]:
unsorted_arr1 = unsorted_arr.copy()

unsorted_arr2 = unsorted_arr.copy()

unsorted_arr3 = unsorted_arr.copy()

unsorted_arr4 = unsorted_arr.copy()

In [1419]:
unsorted_arr1.sort()
print(unsorted_arr1)

# 기본 : axis = -1 (axis = None은 허용 안됨)

[[0.0845008  0.11557521 0.15335899]
 [0.04175934 0.06661383 0.35801565]
 [0.23126106 0.45941345 0.59773814]]


In [1420]:
unsorted_arr2.sort(axis = -1)
print(unsorted_arr2)

# axis = -1 마지막 axis -> 1과 동일

[[0.0845008  0.11557521 0.15335899]
 [0.04175934 0.06661383 0.35801565]
 [0.23126106 0.45941345 0.59773814]]


In [1421]:
unsorted_arr3.sort(axis=0)
print(unsorted_arr3)

[[0.04175934 0.0845008  0.06661383]
 [0.11557521 0.35801565 0.15335899]
 [0.59773814 0.45941345 0.23126106]]


In [1422]:
unsorted_arr4.sort(axis=1)
print(unsorted_arr4)

[[0.0845008  0.11557521 0.15335899]
 [0.04175934 0.06661383 0.35801565]
 [0.23126106 0.45941345 0.59773814]]


* 배열 Slicing
>  - 여러개의 배열 요소를 참조할 때, 슬라이싱 사용
>  - 슬라이싱은 axis 별로 범위 지정해 실행
>  - 범위 : from_index : to_index : step (to_index는 포함 안됨)
>  - 범위 지정에서 from_index 생략 시, 0 간주
>  - 범위 지정에서 to_index 생략 시, 마지막 인덱스로 간주
>  - 전체 범위 = ":"

>  - 슬라이싱은 원본 배열의 view -> 슬라이싱 결과의 요소를 업데이트하면 원본에 반영

In [1423]:
a1 = np.arange(1, 25).reshape((4, 6))
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [1424]:
a1[1:3, 1:5] # 1~2행, 1~4열

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [1425]:
a1[1:-1, 1:-1] # 1~2행(마지막 행 직전), 1~4열(마지막 열 직전)

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [1426]:
a1[1:, :-1]

array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [1427]:
a1[1:3, :]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [1428]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [1429]:
a1[:, [1, 2]]

# 전체 행에 대해, 1,2번 칼럼(열) 참조

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

* 간격 슬라이싱 : 띄워서 슬라이싱

In [1430]:
a1 = np.arange(15).reshape(3, 5)
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [1431]:
a1[:, ::2] # 열 두 칸씩 띄워 슬라이싱

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [1432]:
a1[::2, ::3] # 행은 두 칸씩, 열은 세 칸씩 띄워 슬라이싱

array([[ 0,  3],
       [10, 13]])

* Slicing Update

In [1433]:
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [1434]:
slide_arr = a1[1:3, 1:5]
print(slide_arr)

[[ 6  7  8  9]
 [11 12 13 14]]


In [1435]:
slide_arr[:, 1:3] = 99999
print(slide_arr)

[[    6 99999 99999     9]
 [   11 99999 99999    14]]


In [1436]:
print(a1)

[[    0     1     2     3     4]
 [    5     6 99999 99999     9]
 [   10    11 99999 99999    14]]


* 차원 추가

In [1437]:
arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


In [1438]:
print(arr.shape)

(4,)


* 궁금한 점
>  - 첫 번째 차원 = 행

In [1439]:
arr2 = arr[np.newaxis]
print(arr2)

# 첫 번째 차원에 새 차원 생성

[[1 2 3 4]]


In [1440]:
print(arr2.shape)

(1, 4)


In [1441]:
arr3 = arr[:, np.newaxis] # 새 차원 위치 지정
print(arr3)

[[1]
 [2]
 [3]
 [4]]


In [1442]:
print(arr3.shape)

(4, 1)


* 차원 확장 및 축소

In [1443]:
arr = np.array([[1], [2], [3]])
print(arr)

[[1]
 [2]
 [3]]


In [1444]:
print(arr.shape)

(3, 1)


In [1445]:
expansion = np.expand_dims(arr, axis=0) # 첫 번째 위치 (행) 에 차원 추가
print(expansion)

[[[1]
  [2]
  [3]]]


In [1446]:
print(expansion.shape)

(1, 3, 1)


In [1447]:
reduction = np.squeeze(arr, axis=1) # 두 번째 위치 (열) 의 차원 축소
print(reduction)

[1 2 3]


In [1448]:
print(reduction.shape)

(3,)


In [1449]:
reduction2 = np.squeeze(expansion) # 차원 축소가 가능한 전체 차원 대상으로
print(reduction2)

[1 2 3]


In [1450]:
print(reduction2.shape)

(3,)


* 배열 결합

In [1451]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [1452]:
print(b)

[[ 7  8  9]
 [10 11 12]]


In [1453]:
result = np.concatenate((a, b))
print(result)

# 결합 기본 차원은 axis = 0으로, 행이 늘어남

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1454]:
print(result.shape)

(4, 3)


In [1455]:
result2 = np.concatenate((a, b), axis=1) 
print(result2)

# 열 기준 결합

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [1456]:
print(result2.shape)

(2, 6)


In [1457]:
result3 = np.vstack((a, b))
print(result3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1458]:
print(result3.shape)

(4, 3)


In [1460]:
result4 = np.hstack((a, b))
print(result4)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [1461]:
print(result4.shape)

(2, 6)


* 배열 분리

In [1462]:
a = np.arange(1, 25).reshape((4, 6))
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [1463]:
print(a.shape)

(4, 6)


In [1466]:
result = np.hsplit(a, 3)
print(result)

# column으로 3 그룹 분리 후, 분리된 배열 리스트 반환

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [1469]:
result2 = np.vsplit(a, 2)
print(result2)

#  row로 2 그룹 분리 후, 분리된 배열 리스트 반환

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
